### ISSUE TITLE
現状のバグ・気になる点

### ISSUE THREAD

**Issue by Palrex4999** [Palrex4999/Koara_shooting#4]
- [x] NullPointerExceptionがPlayer.pdeのdrawDebri関数で起きる脆弱性の解決( if(millis() - clushCount < 2000)でアプレット起動時間millis()と1機死亡からの時間の差が2000ミリ秒の間にdrawDebri関数を呼び出しているが、アプレット起動から2000ミリ秒未満の間にEnterキーを押してゲームをスタートするとdebris[]の中身がNullのままdrawDebri関数が呼び出される)
  - clushCount=-1で初期化して上記if文に条件追加すれば解決

- [x] 得点増加の判定が微妙・ボス撃破時の得点増加無し→ヒット・撃破したのに得点増加無しなことがある
  - 得点増加の判定にWorld.pdeでisHitted()を呼び出していたがEnemy.pdeでもisHitted()を呼び出していたため判定が不安定だった
  - ボス撃破時の得点増加を実装する 

- [x] リトライボタンがただゲームシーンに遷移するだけになっている=死んだ時点からやり直し
  - 仕様通りなのかもしれないがボス撃破後のリトライでボスと再戦するようになってるのは直感に反するので全値リセットニューゲームにする

- [x] 弾の数が多いと非常に重い
  - 弾の描画処理方法を改善：sin,cosのメモ化
  - 弾の衝突判定を高速化：4分木空間分割・モートン番号を用いて近傍の弾のみ判定

- [x] ボスの弾 に当たり判定が無い
  - Player.pdeのhitcheckにボスが入っていない

**Comment by YuiSuga** [comment]
やります

**Comment by YuiSuga** [comment]
実装完了しました
