### ISSUE TITLE
敵の抽象クラスの作成(Enemy)

### ISSUE THREAD

**Issue by Palrex4999** [Palrex4999/Koara_shooting#8]
- [x] 敵の抽象クラスの作成
- [x] 拡張の仕方を決める
~~1弾1ダメージのために無敵時間を作る~~
- [x] 自分の弾と敵が当たった時に効果音を出す。

**Comment by Palrex4999** [comment]
とりあえずここやります

**Comment by Palrex4999** [comment]
divideselfとisInvincibleを削除

**Comment by Palrex4999** [comment]
効果音系は後に回します

**Comment by YuiSuga** [comment]
原因が特定できてないんですが、敵の消滅時、画面内にあるその敵が発射した弾も同時に消滅してしまっているみたいです
