### ISSUE TITLE
グラフィック作成および実装

### ISSUE THREAD

**Issue by Palrex4999** [Palrex4999/Koara_shooting#9]
- [x] 自機猫
- [x] 敵ねずみ
- [x] 背景
- [x] パーティクル
- [x] エフェクト

**Comment by Palrex4999** [comment]
背景
![night_sky](https://user-images.githubusercontent.com/48020270/103151360-c89da680-47c0-11eb-9dd6-fcc2d3c2f633.png)

**Comment by Palrex4999** [comment]
プレイヤーネッコ
![cat](https://user-images.githubusercontent.com/48020270/103151366-d7845900-47c0-11eb-9a12-88674a6003eb.png)

**Comment by Palrex4999** [comment]
敵ネズミ
![mouse_blue](https://user-images.githubusercontent.com/48020270/103151828-e8cf6480-47c4-11eb-9953-35fb17c67b1a.png)
![mouse_white](https://user-images.githubusercontent.com/48020270/103151829-e967fb00-47c4-11eb-9352-361885dfc6a2.png)

**Comment by Palrex4999** [comment]
サカナ(これはフリー素材)←敵の弾とかにする？
![fishes](https://user-images.githubusercontent.com/48020270/103152087-d60a5f00-47c7-11eb-9b5c-74c403d755b1.png)

**Comment by Palrex4999** [comment]
プレイヤーの弾を何にするか。ネズミが嫌いなものか、猫が好きなものにする？？？？
鯛焼き
![taiyaki](https://user-images.githubusercontent.com/48020270/103203047-7763f300-4937-11eb-946e-95c79a16e974.png)
缶詰
![kanzume](https://user-images.githubusercontent.com/48020270/103206333-f872b880-493e-11eb-84cc-fb8432146e1a.png)

**Comment by YuiSuga** [comment]
大変反応遅くなりました！
数々の素晴らしいドット絵提供感謝
敵の弾をサカナにするとプレイヤーの弾か敵の弾か区別つきづらくなりそうなので、プレイヤーの弾を猫の好物・猫要素のあるものにして、敵の弾はネズミの好物・ネズミっぽいもの（チーズとか）にするのはどうでしょう

**Comment by Palrex4999** [comment]
確かに！
プレイヤーの弾→サカナ
敵の弾→チーズ
がいいかもしれない

**Comment by Palrex4999** [comment]
チーーーーーーず
![cheese](https://user-images.githubusercontent.com/48020270/103264548-58746800-49ee-11eb-9a33-54cc2f0b2b65.png)
